%{
The following is a start up script with configures a variety of settings
and file paths to make sure all of the codebase features work correctly.
%}

clc
close all
clear

%% Add files to search path

%Get the current project 
try
    prj = currentProject;
catch
    error("Incorrect procedure. Open the project first and then run the startup script.")
end

%Get all relevant paths to the project
root_path = prj.RootFolder;
src_path = fullfile(root_path,'src');
temclearTempp_path = fullfile(src_path,'temp');
inits_path = fullfile(src_path,'inits');
user_data_path = temp_path;
startup_path = fullfile(root_path,'project_startup');%add all necessary paths to the project path so it can see them
closedown_path = fullfile(root_path,'project_closedown');
cache_path = fullfile(root_path,'codegen','slprj_and_caches');
asv_path = fullfile(root_path,'codegen','autosaves');
test_path = fullfile(root_path,'src/tests/');

%Adding necessary paths
addpath(root_path);
addpath(startup_path);
addpath(closedown_path);

%Adding Subfolders
src_sub_folders = string(genpath(src_path));
src_sub_folders = split(src_sub_folders, pathsep);

%Remove Empty Entries from pathsep
src_sub_folders(src_sub_folders=="") = [];

%Convert to cell array for addpath
src_sub_folders = cellstr(src_sub_folders);

warningState = warning('off','all');

%add them all to the path
addpath(src_sub_folders{:});
warning(warningState);

%% Check for and/or create missing folders
if(~isfolder(root_path))
    error("You may have changed the name of the simulation folder. Please make sure you are within 'ODIN_Simulink'.")
end

if(~isfolder(src_path))
    error("YOu are missing the src folder. Quickest solution will be to reclone the Repo.")
end

if(~isfolder(temp_path))
    fprintf("Folder for temporary files is missing. Creating it now.\n")
    mkdir(temp_path);
end

if(~isfolder(cache_path))
    fprintf("Creating folder for autogenerated files.\n")
    mkdir(cache_path);
end

if(~isfolder(asv_path))
    fprintf("Creating autosaves folder.\n")
    mkdir(asv_path);
end

if(~isfolder(inits_path))
    error("Missing inits folder, please reclone the Repo.")
end

if(~isfolder(startup_path))
    error("Missing Project Startup Path, please reclone the Repo.")
end

if(~isfolder(closedown_path))
    error("Missing Project Closedown Path, please reclone the Repo.")
end

if(~isfolder(user_data_path))
    fprintf("Folder for data outputs is missing. Creating it now. \n")
    mkdir(user_data_path)
end

%create a variable
prj_path_list.root_path = root_path;
prj_path_list.src_path = src_path;
prj_path_list.temp_path = temp_path;
prj_path_list.inits_path = inits_path;
prj_path_list.user_data_path = user_data_path;
prj_path_list.cache_path = cache_path;
prj_path_list.asv_path = asv_path;
prj_path_list.startup_path = startup_path;
prj_path_list.closedown_path = closedown_path;
save(fullfile(startup_path,"prj_path_list.mat"),"prj_path_list",'-mat');

cd(prj_path_list.root_path)
fprintf("Filepaths configured successfully. Moving you to the project root folder. \n")

%% Configure file path for automatically generated temporary files

try
    Simulink.fileGenControl('set',...
        'CacheFolder',cache_path,....
        'CodeGenFolder',cache_path);
    fprintf("Cache and CodeGen file paths are set up.\n")
catch
    fprintf("Unable to configure cache and codegen files. You might be in a OneDrive file, move out of it.\n");
end

Simulink.fileGenControl('set',...
    'CacheFolder',cache_path,...
    'CodeGenFolder',cache_path);
prj.SimulinkCacheFolder = cache_path;
prj.SimulinkCodeGenFolder = cache_path;

fprintf("Cache and CodeGen file paths are setup.\n");

%% Clear Temporary folder for a clean workspace if there is anything in it.

%suppress warnings for removed temp files
warningState = warning('off','all');
clear_temp();
warning(warningState);
fprintf("Temporary files have been cleared out.\n");

