%{
The following is a start up script with configures a variety of settings
and file paths to make sure all of the codebase features work correctly.
%}

clc
close all

%% Add files to search path

%Get the current project 
try
    prj = currentProject;
catch
    error("Incorrect procedure. Open the project first and then run the startup script.")
end

%Get all relevant paths to the project
root_path = prj.RootFolder;
src_path = fullfile(root_path,'src');
temp_path = fullfile(src_path,'temp');
inits_path = fullfile(src_path,'inits');
user_data_path = temp_path;
startup_path = fullfile(root_path,'project_startup');%add all necessary paths to the project path so it can see them
closedown_path = fullfile(root_path,'project_closedown');
cache_path = fullfile(root_path,'codegen','slprj_and_caches');
asv_path = fullfile(root_path,'codegen','autosaves');
test_path = fullfile(root_path,'src/tests/');

%Adding necessary paths
addpath(root_path);
addpath(startup_path);
addpath(closedown_path);

%Adding Subfolders
src_sub_folders = string(genpath(src_path));
src_sub_folders = split(src_sub_folders, pathsep);

%Remove Empty Entries from pathsep
src_sub_folders(src_sub_folders=="") = [];

%Convert to cell array for addpath
src_sub_folders = cellstr(src_sub_folders);

warningState = warning('off','all');

%add them all to the path
addpath(src_sub_folders{:});
warning(warningState);

%% Check for and/or create missing folders
if(~isfolder(root_path))
    error("You may have changed the name of the simulation folder. Please make sure you are within 'ODIN_Simulink'.")
end

if(~isfolder(src_path))
    error("YOu are missing the src folder. Quickest solution will be to reclone the Repo.")
end

if(~isfolder(temp_path))
    fprintf("Folder for temporary files is missing. Creating it now.\n")
    mkdir(temp_path);
end

if(~isfolder(cache_path))
    fprintf("Creating folder for autogenerated files.\n")
    mkdir(cache_path);
end

if(~isfolder(asv_path))
    fprintf("Creating autosaves folder.\n")
    mkdir(asv_path);
end

if(~isfolder(inits_path))
    error("Missing inits folder, please reclone the Repo.")
end

if(~isfolder(startup_path))
    error("Missing Project Startup Path, please reclone the Repo.")
end

if(~isfolder(closedown_path))
    error("Missing Project Closedown Path, please reclone the Repo.")
end

